### ISSUE TITLE
Ensure it works offline correctly

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#19]

**Comment by lazerwalker** [comment]
I agree, but worth calling out for the sake of argument that this means it'll make it obvious to folks it isn't real-time multiplayer. I think that's the right tradeoff /shrug

**Comment by lazerwalker** [comment]
Things to think about:

- Cache a local copy of the app bundle, and have a way to update to the latest over-the-air
- If offline players can submit scores, make sure that every code deploy bumps the seed / API version so that data hitting the server is always for the correct version
- If somebody's phone is always in airplane mode, when seeds (or trial mode) flip over they'll presumably commonly hit situations with no good recording data. Obvious options are (a) accept that's fine and know they'll get a slightly sub-par experience and/or (b) strongly nudge them towards going online

**Comment by orta** [comment]
Step 1: Firebase is synchronous right now, and that takes a while to timeout

I think it's fine to disable the Royale mode for offline, but keep the vs the top scores mode if we've got any recordings for ti

**Comment by lazerwalker** [comment]
Moving here from iMessage thread:

I’m thinking instead of writing some fiddly code to store the webapp to disk (and have to deal with whether or not to explicitly download images, etc), we just set it up as a proper offline webapp and let the web view cache it for us:

https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/SafariJSDatabaseGuide/OfflineApplicationCache/OfflineApplicationCache.html

Only problem is we’ll need to host somewhere other than GH Pages since we can’t set MIME type

**Comment by lazerwalker** [comment]
There's an implementation of Service Workers in master, but they don't work from within a WKWebView.

Also need caching for Firebase DB calls, as that's currently stalling offline Safari access. My first step is to check what sort of client-side caching layer Firebase provides (if any), and assuming not then add a caching layer in front of our Firebase calls that store to localstorage or a SQLite db (probably localstorage)

**Comment by lazerwalker** [comment]
I need to do a whole bunch of testing on-device, but this theoretically works.

* On launch, if a new build of the app exists, it's downloaded and the user is prompted to refresh the app (we'll eventually make this nicer: #26)

* When the user fetches seeds, we cache that result. If the network request fails, we use the last fetched batch of seeds

* When the user requests recordings for a given seed, we store that, only keeping the most recent 51 seeds (50 royales + 1 daily, although our code doesn't distinguish). If the network request fails, we try to grab from there before returning an empty replay object.

This means both royale and trial should work offline.
