### ISSUE TITLE
Trial is down

### ISSUE THREAD

**Issue by orta** [flappy-royale/flappy-royale#202]
Noticed late tonigh, I'll look tomorrow

**Comment by lazerwalker** [comment]
Argh, there were a handful of issues with cloud fn stuff. Today's the first time we've seen it run after a daily trial switchover, so that shook out some bugs. 

We'll be killing daily trial running through this flow soon anyway (since we won't need replays when using PlayFab leaderboards), but at least this is ironing out bugs we'd run into when trying to up the number of royale seeds.

Pushed, migration manually run, tested on prod.
